#!/usr/bin/env bash

export IFS='
'

# Default gateway IPv4 Address
export GATEWAY_IP=`ip route show | grep default | awk '{ print $3; }'`

export FORWARDER=""
export DELIMITER=""


# Find the authoritative DNS from environment variables
for i in `env | grep RECURSOR_ | sort -r`; do

    # Get environment variables names and values
    export VARNAM=`echo "${i}" | cut -d '=' -f 1`
    export VARVAL=`echo "${i}" | cut -d '=' -f 2`

    # xargs to trim whitespaces
    # tr to translate uppercase to lowercase
    export DOMAIN=`echo ${VARVAL} | cut -d ':' -f 1 | xargs`
    export PORT=`echo ${VARVAL}  | cut -s -d ':' -f 2 | xargs`
    if [ -z "${PORT}" ]; then
	export PORT=53
    fi

    # Show what we are doing...
    echo DOMAIN: $DOMAIN
    echo PORT: $PORT

    # Add domain to comma-separated string
    export FORWARDER="${FORWARDER}${DELIMITER}${DOMAIN}=${GATEWAY_IP}:${PORT}"
    export DELIMITER=","

done
echo FORWARDER: $FORWARDER

# Start the recursor server at port 53
exec /usr/sbin/pdns_recursor --setuid=pdns --setgid=pdns \
    --daemon=no --local-address=0.0.0.0 --local-port=53  \
    --forward-zones="${FORWARDER}"
